In [41]:
import numpy as np
import torch

In [42]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [43]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [44]:
# Convert the inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## **Linear Regression**

In [45]:
# Weights and biases
w = torch.randn(2,3,requires_grad = True)
b = torch.randn(2,requires_grad = True)

print(w)
print(b)

tensor([[ 0.6239,  0.5156,  0.7655],
        [ 1.6520, -0.8818,  0.9803]], requires_grad=True)
tensor([-0.3677,  0.0056], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a normal distribution.

In [46]:
def model(x):
  return x @ w.t() + b

# @ represents matrix multiplication, and .t() returns transpose of matrix in pyTorch

In [47]:
preds = model(inputs)
print(preds)

tensor([[112.6335, 103.6703],
        [150.7651, 135.4739],
        [167.3942,  82.4216],
        [113.7583, 166.8584],
        [145.7577,  97.9584]], grad_fn=<AddBackward0>)


In [48]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## **Loss function**

In [49]:
def mse(t1,t2):
  diff = (t1 - t2)
  return torch.sum(diff * diff) / diff.numel()

In [50]:
loss = mse(preds,targets)
print(loss)

tensor(4285.0586, grad_fn=<DivBackward0>)


## **Adjust weights and biases using gradient descent**

In [51]:
preds = model(inputs)
print(preds)

tensor([[112.6335, 103.6703],
        [150.7651, 135.4739],
        [167.3942,  82.4216],
        [113.7583, 166.8584],
        [145.7577,  97.9584]], grad_fn=<AddBackward0>)


In [52]:
# Calculate loss
loss = mse(preds,targets)
print(loss)

tensor(4285.0586, grad_fn=<DivBackward0>)


In [53]:
# Calculate gradient
loss.backward()
print(w.grad)
print(b.grad)

tensor([[5400.5581, 4893.7881, 3219.0332],
        [2597.6851,  415.2062,  810.4913]])
tensor([61.8618, 25.2765])


In [54]:
# Update weights and biases
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [55]:
print(w)
print(b)

tensor([[ 0.5699,  0.4667,  0.7333],
        [ 1.6260, -0.8860,  0.9722]], requires_grad=True)
tensor([-0.3683,  0.0053], requires_grad=True)


In [56]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(3635.4915, grad_fn=<DivBackward0>)


## **Train for multiple epochs**

In [57]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

    w.grad.zero_()
    b.grad.zero_()

In [58]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(662.7906, grad_fn=<DivBackward0>)


In [59]:
preds

tensor([[ 61.1931,  80.7535],
        [ 85.1745, 110.3617],
        [105.4671,  94.1257],
        [ 44.8806,  97.9871],
        [ 93.1211, 100.4168]], grad_fn=<AddBackward0>)

In [60]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

##**Linear Regression using PyTorch built-ins**

In [61]:
import torch.nn as nn

In [62]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [63]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

## **Dataset and DataLoader**

In [64]:
from torch.utils.data import TensorDataset

In [65]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [66]:
from torch.utils.data import DataLoader

In [67]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [68]:
for xb,yb in train_dl:
  print("Batch:")
  print(xb)
  print(yb)

Batch:
tensor([[ 68.,  97.,  70.],
        [101.,  44.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 135.,  57.],
        [ 92.,  87.,  64.]])
tensor([[102., 120.],
        [ 21.,  38.],
        [ 81., 101.],
        [118., 134.],
        [ 82., 100.]])
Batch:
tensor([[ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [103.,  43.,  36.],
        [102.,  43.,  37.],
        [ 68.,  96.,  71.]])
tensor([[ 57.,  69.],
        [ 80., 102.],
        [ 20.,  38.],
        [ 22.,  37.],
        [104., 118.]])
Batch:
tensor([[ 74.,  66.,  43.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 88., 134.,  59.],
        [ 87., 134.,  58.]])
tensor([[ 57.,  69.],
        [103., 119.],
        [ 56.,  70.],
        [118., 132.],
        [119., 133.]])


## **nn.Linear**

In [70]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3533, -0.4668, -0.1839],
        [ 0.3180, -0.0064, -0.2755]], requires_grad=True)
Parameter containing:
tensor([0.2251, 0.0023], requires_grad=True)


In [71]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3533, -0.4668, -0.1839],
         [ 0.3180, -0.0064, -0.2755]], requires_grad=True),
 Parameter containing:
 tensor([0.2251, 0.0023], requires_grad=True)]

In [72]:
preds = model(inputs)
preds

tensor([[-13.1618,  10.9422],
        [-20.4653,  10.7468],
        [-42.2459,  10.8317],
        [  9.3899,  21.9720],
        [-33.0757,   2.0460],
        [-12.3417,  11.2666],
        [-20.1824,  10.4778],
        [-42.0764,  10.8742],
        [  8.5698,  21.6475],
        [-33.6129,   1.4525],
        [-12.8789,  10.6731],
        [-19.6452,  11.0712],
        [-42.5287,  11.1007],
        [  9.9271,  22.5655],
        [-33.8958,   1.7216]], grad_fn=<AddmmBackward0>)

##**Loss Function**

In [73]:
import torch.nn.functional as F

In [74]:
loss_fn = F.mse_loss

In [75]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(10006.8594, grad_fn=<MseLossBackward0>)


# **Optimizer-Gradient Descent**

In [76]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [77]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [78]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 711.8519
Epoch [20/100], Loss: 616.8590
Epoch [30/100], Loss: 241.7967
Epoch [40/100], Loss: 392.0494
Epoch [50/100], Loss: 69.8103
Epoch [60/100], Loss: 200.7023
Epoch [70/100], Loss: 148.3396
Epoch [80/100], Loss: 36.5066
Epoch [90/100], Loss: 68.5748
Epoch [100/100], Loss: 34.4949


In [79]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 59.0268,  72.1855],
        [ 80.9347,  97.0213],
        [117.8628, 138.4204],
        [ 32.0097,  47.2807],
        [ 93.4271, 106.7870],
        [ 58.0244,  71.2227],
        [ 80.4537,  96.3629],
        [118.0478, 138.6656],
        [ 33.0121,  48.2436],
        [ 93.9484, 107.0914],
        [ 58.5458,  71.5271],
        [ 79.9323,  96.0585],
        [118.3439, 139.0788],
        [ 31.4884,  46.9764],
        [ 94.4295, 107.7499]], grad_fn=<AddmmBackward0>)

In [80]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])