In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1.,2.,3.,4.])
t2

tensor([1., 2., 3., 4.])

In [6]:
# 3-Dimensional Array
t3 = torch.tensor([[[11,12,13],
                    [14,15,16],
                    [17,18,19]]])
t3

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [7]:
t3.shape

torch.Size([1, 3, 3])

## **Tensor Opeartions and gradients**

In [8]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad = True)

In [9]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [10]:
#Computing the derivative
y.backward()

In [11]:
# Displaying the gradients
print("dy/dx",x.grad) # Returns as requires_grad = True not specified
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


## **Operatibility with Numpy**

In [12]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])

In [13]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [14]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [15]:
z = y.numpy()
z

array([[1, 2],
       [3, 4],
       [5, 6]])

Tensors in PyTorch support a variety of operations, and what we've covered here is by no means exhaustive. You can learn more about tensors and tensor operations here: https://pytorch.org/docs/stable/tensors.html